CREATE LOGIN [MSSQLSERVER\grupa1] FROM WINDOWS WITH DEFAULT_DATABASE=[AdventureWorks], DEFAULT_LANGUAGE=[us_english];
EXEC sp_denylogin 'MSSQLSERVER\grupa2';
ALTER LOGIN [MSSQLSERVER\grupa2] WITH DEFAULT_DATABASE =[AdventureWorks];

